enable-magisk-update = true # set this to false if you do not want to receive updates for the module in magisk app
parallel-jobs = 1
cli-source = "MorpheApp/morphe-cli"
patches-source = "MorpheApp/morphe-patches"

# add 'enabled = false' for not patching a specific app or remove it from the config
# see https://github.com/j-hc/revanced-magisk-module/blob/main/CONFIG.md for more detailed explanations

# you can use rvmm-config-gen to generate a config

[Music]
#enabled = false
app-name = "Music"
build-mode = "both"
arch = "arm64-v8a"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music"
uptodown-dlurl = "https://youtube-music.en.uptodown.com/android"
excluded-patches = """\
  'Custom branding' \
  """

[YouTube]
#enabled = false
app-name = "YouTube"
build-mode = "both"
arch = "arm64-v8a"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube"
uptodown-dlurl = "https://youtube.en.uptodown.com/android"
excluded-patches = """\
  'Custom branding' \
  """

[Reddit]
enabled = true
dpi = "120-640dpi"
apkmirror-dlurl = "https://www.apkmirror.com/apk/redditinc/reddit/"

[News]
enabled = false
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/google-news"

[Photomath]
enabled = false
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/photomath"
dpi = "120-640dpi"

[Spotify]
enabled = false
uptodown-dlurl = "https://spotify.en.uptodown.com/android"
#archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.spotify.music"
arch = "arm64-v8a"

#[Backdrops]
#uptodown-dlurl = "https://backdrops.en.uptodown.com/android"
